export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAILURE = "GET_MOVIES_FAILURE";
export const POST_MOVIE_REQUEST = "POST_MOVIE_REQUEST";
export const POST_MOVIE_SUCCESS = "POST_MOVIE_SUCCESS";
export const POST_MOVIE_FAILURE = "POST_MOVIE_FAILURE";
export const GET_ALL_ACTORS = "GET_ALL_ACTORS";
export const GET_ALL_PRODUCERS = "GET_ALL_PRODUCERS";
